//action
export const SET_COURSES = 'set_course'
export const SET_TOPICS = 'set_topics'
export const SET_COURSEDETAIL = 'set_coursedetail'
export const SET_ACTIVE = 'set_active'
export const SET_FIRSTID = 'set_firstID'
export const SET_LASTID = 'set_lastID'
export const SET_VALUETAKENOTE = 'set_valueTakeNote'
export const SET_CURRENTTIMEVIDEOPLAY = 'set_currentTimeVideoPlay'
export const SET_TOTALTIME = 'set_totalTime'
export const SET_FOUCESTIME = 'set_foucesTime'
export const PLAYVIDEO = 'playvideo'
export const PLAYING = 'playing'
export const HASPLAYED = 'hasPlayed'
export const ACTIVETAKENOTE = 'activeTakenote'
export const ACTIVECREATETAKENOTE = 'activeCreateTakeNote'
